site_name: TrendFocus | JonasSLara

nav:
  - Home: index.md
  - Desenvolvedores: devs.md
  - Deploy: deploy.md
  - Tecnologias: stack.md
  - Artefatos: artefatos.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate