-- =====================================
-- INSERÇÃO DE NOTÍCIAS INICIAIS
-- =====================================

INSERT INTO noticia (titulo, resumo, url_original, url_imagem, data_publicacao, data_coleta, fonte) VALUES
('Avanços na Agricultura Regenerativa impulsionam produção sustentável',
 'Pesquisadores destacam novas práticas regenerativas que aumentam produtividade e reduzem impacto ambiental.',
 'https://agro.ufsm.br/noticias/agricultura-regenerativa',
 'https://imagens.ufsm.br/agricultura.jpg',
 NOW() - INTERVAL '30 days',
 NOW(),
 'UFSM Agro'),

('Cultivo Orgânico cresce 20% no Brasil em 2025',
 'Estudo aponta que o cultivo orgânico vem ganhando força nas pequenas propriedades.',
 'https://agro.ufsm.br/noticias/cultivo-organico',
 'https://imagens.ufsm.br/cultivo.jpg',
 NOW() - INTERVAL '25 days',
 NOW(),
 'Embrapa'),

('Uso de suplementos naturais melhora a qualidade do leite',
 'Pesquisa avalia o impacto da suplementação animal natural na produção leiteira.',
 'https://revistaagro.com.br/suplementacao-animal',
 'https://imagens.ufsm.br/leite.jpg',
 NOW() - INTERVAL '20 days',
 NOW(),
 'Revista Agro'),

('Descoberta de nova sequência genética amplia estudos sobre biodiversidade',
 'Geneticistas da UFSM identificam uma sequência de DNA inédita em espécies amazônicas.',
 'https://biologia.ufsm.br/noticias/dna-recombinante',
 'https://imagens.ufsm.br/dna.jpg',
 NOW() - INTERVAL '18 days',
 NOW(),
 'UFSM Bio'),

('Mutação genética pode aumentar resistência a doenças em plantas',
 'Pesquisadores analisam mutações genéticas benéficas em culturas agrícolas.',
 'https://biogen.ufsm.br/noticias/mutacao-genetica',
 'https://imagens.ufsm.br/planta-mutacao.jpg',
 NOW() - INTERVAL '15 days',
 NOW(),
 'BioGen UFSM'),

('Estudo sobre plasticidade cerebral traz novas abordagens para reabilitação',
 'Pesquisadores desenvolvem terapia baseada em estímulos cognitivos.',
 'https://saude.ufsm.br/noticias/plasticidade-cerebral',
 'https://imagens.ufsm.br/mente.jpg',
 NOW() - INTERVAL '14 days',
 NOW(),
 'UFSM Saúde'),

('Imunização avança com vacinas de RNA sintético',
 'Novas tecnologias prometem imunizantes mais rápidos e eficazes.',
 'https://saude.gov.br/noticias/imunizacao-rna',
 'https://imagens.ufsm.br/vacina.jpg',
 NOW() - INTERVAL '13 days',
 NOW(),
 'Ministério da Saúde'),

('Simulação numérica otimiza previsão climática',
 'Modelos computacionais tornam previsões mais precisas em curtos prazos.',
 'https://clima.ufsm.br/noticias/simulacao-numerica',
 'https://imagens.ufsm.br/clima.jpg',
 NOW() - INTERVAL '12 days',
 NOW(),
 'UFSM Exatas'),

('Geoprocessamento ajuda no monitoramento de áreas desmatadas',
 'Técnicas de sensoriamento remoto contribuem para controle ambiental.',
 'https://terra.ufsm.br/noticias/geoprocessamento-desmatamento',
 'https://imagens.ufsm.br/satelite.jpg',
 NOW() - INTERVAL '10 days',
 NOW(),
 'UFSM Terra'),

('Modelagem matemática aplicada a epidemias apresenta resultados promissores',
 'Matemáticos simulam cenários de contágio com maior precisão.',
 'https://exatas.ufsm.br/noticias/modelagem-epidemias',
 'https://imagens.ufsm.br/grafico.jpg',
 NOW() - INTERVAL '9 days',
 NOW(),
 'Revista Exatas'),

('Comportamento social em tempos digitais é tema de estudo interdisciplinar',
 'Pesquisadores investigam os efeitos das redes sociais sobre interações humanas.',
 'https://humanas.ufsm.br/noticias/comportamento-social',
 'https://imagens.ufsm.br/social.jpg',
 NOW() - INTERVAL '8 days',
 NOW(),
 'UFSM Humanas'),

('Pensamento crítico é essencial na formação de professores',
 'Docentes destacam a importância da reflexão nas práticas pedagógicas.',
 'https://educacao.ufsm.br/noticias/pensamento-critico',
 'https://imagens.ufsm.br/educacao.jpg',
 NOW() - INTERVAL '7 days',
 NOW(),
 'UFSM Educação'),

('Gestão pública ganha eficiência com ferramentas digitais',
 'Novas plataformas melhoram a transparência e a tomada de decisão.',
 'https://sociais.ufsm.br/noticias/gestao-publica',
 'https://imagens.ufsm.br/gestao.jpg',
 NOW() - INTERVAL '6 days',
 NOW(),
 'UFSM Sociais'),

('Política fiscal é revisada para impulsionar economia verde',
 'Economistas propõem incentivos fiscais voltados à sustentabilidade.',
 'https://sociais.ufsm.br/noticias/politica-fiscal',
 'https://imagens.ufsm.br/economia.jpg',
 NOW() - INTERVAL '5 days',
 NOW(),
 'UFSM Economia'),

('Engenharia de nanotecnologia cria materiais autorreparáveis',
 'Novos compostos podem se regenerar após danos estruturais leves.',
 'https://engenharias.ufsm.br/noticias/nanotecnologia',
 'https://imagens.ufsm.br/nano.jpg',
 NOW() - INTERVAL '4 days',
 NOW(),
 'UFSM Engenharia'),

('Inteligência artificial é usada para prever falhas em pontes',
 'Sensores inteligentes analisam estruturas em tempo real.',
 'https://engenharias.ufsm.br/noticias/ia-pontes',
 'https://imagens.ufsm.br/ponte.jpg',
 NOW() - INTERVAL '3 days',
 NOW(),
 'UFSM Engenharia Civil'),

('Análise textual automatizada apoia estudos linguísticos',
 'Sistema identifica padrões sintáticos em grandes volumes de texto.',
 'https://linguistica.ufsm.br/noticias/analise-textual',
 'https://imagens.ufsm.br/texto.jpg',
 NOW() - INTERVAL '2 days',
 NOW(),
 'UFSM Letras'),

('Comparatismo literário ganha destaque em novos estudos acadêmicos',
 'Pesquisadores exploram influências cruzadas entre literaturas modernas.',
 'https://artes.ufsm.br/noticias/comparatismo-literario',
 'https://imagens.ufsm.br/literatura.jpg',
 NOW() - INTERVAL '1 day',
 NOW(),
 'UFSM Artes'),

('Uso de IA no ensino personalizado cresce em 2025',
 'Ferramentas inteligentes ajudam professores a adaptar conteúdos aos alunos.',
 'https://educacao.ufsm.br/noticias/ia-no-ensino',
 'https://imagens.ufsm.br/ia-educacao.jpg',
 NOW(),
 NOW(),
 'UFSM Inovação'),

('Nanotecnologia aplicada à saúde promete novos tratamentos',
 'Pesquisas buscam uso de nanopartículas em terapias contra o câncer.',
 'https://engenharias.ufsm.br/noticias/nanotecnologia-saude',
 'https://imagens.ufsm.br/nanosaude.jpg',
 NOW(),
 NOW(),
 'UFSM Engenharia Biomédica');

-- =====================================
-- RELAÇÃO NOTÍCIA ↔ TERMO-CHAVE
-- =====================================
INSERT INTO noticia_termo (noticia_id, termo_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 6),
(6, 8),
(7, 9),
(8, 10),
(9, 11),
(10, 12),
(11, 14),
(12, 13),
(13, 17),
(14, 16),
(15, 18),
(16, 19),
(17, 20),
(18, 20),
(19, 19),
(20, 18);

